/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.vianna.finance.view.financialgoal;

import br.edu.vianna.finance.dao.imp.FinancialGoalDAO;
import br.edu.vianna.finance.model.finances.FinancialGoal;
import br.edu.vianna.finance.model.users.Client;
import br.edu.vianna.finance.utils.dateForm.DateFormat;
import br.edu.vianna.finance.utils.valueForm.ValueFormat;
import br.edu.vianna.finance.view.viewPrincipal;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author Renan Guedes
 */
public class ViewListFinancialGoals extends javax.swing.JDialog {

    /**
     * Creates new form viewListFinancialGoals
     */
    public ViewListFinancialGoals(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.darkGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSearchButton = new javax.swing.JButton();
        jCheckBoxCompleted = new javax.swing.JCheckBox();
        jCheckBoxAllGoals = new javax.swing.JCheckBox();
        jReturnButton = new javax.swing.JButton();
        jCheckBoxCurrentGoals = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGoals = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jExitButton = new javax.swing.JButton();
        jChangeButton = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();
        jRegisterButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(70, 73, 75));
        setMinimumSize(new java.awt.Dimension(803, 630));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(354, 70));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("METAS FINANCEIRAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(76, 76, 76));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jSearchButton.setBackground(new java.awt.Color(0, 102, 51));
        jSearchButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jSearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-Button-search.png"))); // NOI18N
        jSearchButton.setText("  Pesquisar");
        jSearchButton.setMaximumSize(new java.awt.Dimension(82, 29));
        jSearchButton.setMinimumSize(new java.awt.Dimension(82, 29));
        jSearchButton.setPreferredSize(new java.awt.Dimension(110, 29));
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });

        jCheckBoxCompleted.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBoxCompleted.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxCompleted.setText("  Metas cumpridas");
        jCheckBoxCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCompletedActionPerformed(evt);
            }
        });

        jCheckBoxAllGoals.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBoxAllGoals.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxAllGoals.setText("  Todas as metas");
        jCheckBoxAllGoals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAllGoalsActionPerformed(evt);
            }
        });

        jReturnButton.setBackground(new java.awt.Color(0, 102, 51));
        jReturnButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jReturnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-Button-return.png"))); // NOI18N
        jReturnButton.setText("  Voltar");
        jReturnButton.setMaximumSize(new java.awt.Dimension(82, 29));
        jReturnButton.setMinimumSize(new java.awt.Dimension(82, 29));
        jReturnButton.setPreferredSize(new java.awt.Dimension(110, 29));
        jReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReturnButtonActionPerformed(evt);
            }
        });

        jCheckBoxCurrentGoals.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBoxCurrentGoals.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxCurrentGoals.setText("  Metas não cumpridas");
        jCheckBoxCurrentGoals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCurrentGoalsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxAllGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxCurrentGoals))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 481, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jReturnButton, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxCurrentGoals)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jCheckBoxAllGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        jTableGoals.setBackground(new java.awt.Color(255, 255, 255));
        jTableGoals.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTableGoals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Meta", "Descrição", "Valor", "Valor Acumulado", "Data Inicial", "Data Final", "Meses Faltantes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableGoals.setRowHeight(35);
        jTableGoals.setRowMargin(5);
        jTableGoals.setRowSelectionAllowed(false);
        jTableGoals.setShowGrid(false);
        jTableGoals.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(jTableGoals);

        jPanel2.setBackground(new java.awt.Color(76, 76, 76));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jExitButton.setBackground(new java.awt.Color(0, 102, 51));
        jExitButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-Button-cancel.png"))); // NOI18N
        jExitButton.setText("Sair");
        jExitButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jExitButton.setMaximumSize(new java.awt.Dimension(82, 29));
        jExitButton.setMinimumSize(new java.awt.Dimension(82, 29));
        jExitButton.setPreferredSize(new java.awt.Dimension(110, 29));
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jChangeButton.setBackground(new java.awt.Color(0, 102, 51));
        jChangeButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jChangeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-Button-alter.png"))); // NOI18N
        jChangeButton.setText("Alterar");
        jChangeButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jChangeButton.setPreferredSize(new java.awt.Dimension(110, 29));
        jChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChangeButtonActionPerformed(evt);
            }
        });

        jDeleteButton.setBackground(new java.awt.Color(0, 102, 51));
        jDeleteButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-Button-delete.png"))); // NOI18N
        jDeleteButton.setText("Excluir");
        jDeleteButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jDeleteButton.setMaximumSize(new java.awt.Dimension(82, 29));
        jDeleteButton.setMinimumSize(new java.awt.Dimension(82, 29));
        jDeleteButton.setPreferredSize(new java.awt.Dimension(110, 29));
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });

        jRegisterButton.setBackground(new java.awt.Color(0, 102, 51));
        jRegisterButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRegisterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-Button-check.png"))); // NOI18N
        jRegisterButton.setText("Cadastrar");
        jRegisterButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jRegisterButton.setMaximumSize(new java.awt.Dimension(82, 29));
        jRegisterButton.setMinimumSize(new java.awt.Dimension(82, 29));
        jRegisterButton.setPreferredSize(new java.awt.Dimension(110, 29));
        jRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            c = (Client) viewPrincipal.getUser();
            listOfFinancialGoals = new FinancialGoalDAO().searchFinancialGoalClient(c);
            c.setListOfFinancialGoal(listOfFinancialGoals);
            listOfFinancialGoalsFounded = new ArrayList<>(listOfFinancialGoals);
            jCheckBoxCompleted.setSelected(false);
            jCheckBoxCurrentGoals.setSelected(false);
            jCheckBoxAllGoals.setSelected(true);
            fillTable(listOfFinancialGoals);
        }catch (SQLException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Erro: não foi possível carregar suas receitas!");
        }
    }//GEN-LAST:event_formWindowOpened

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        listOfFinancialGoalsFounded.clear();
        if(jCheckBoxAllGoals.isSelected() && jCheckBoxCurrentGoals.isSelected() || jCheckBoxAllGoals.isSelected() && jCheckBoxCompleted.isSelected()
                || jCheckBoxCompleted.isSelected() && jCheckBoxCurrentGoals.isSelected()){
            JOptionPane.showMessageDialog(null, "Erro: Selecione apenas um campo!");
            jCheckBoxAllGoals.setSelected(false);
            jCheckBoxCurrentGoals.setSelected(false);
            jCheckBoxCompleted.setSelected(false);
        }else{
            fillListFounded();
            fillTable(listOfFinancialGoalsFounded);
        }
    }//GEN-LAST:event_jSearchButtonActionPerformed

    private void jChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChangeButtonActionPerformed
        int row = jTableGoals.getSelectedRow();
        if(row <= -1){
            JOptionPane.showMessageDialog(null, "Para alterar uma meta financeira é necessário selecioná-la!");
        }else{
            if(!listOfFinancialGoals.get(row).getCompleted() || !listOfFinancialGoalsFounded.get(row).getCompleted()){
                ViewRegisterFinancialGoal vrfg = new ViewRegisterFinancialGoal(null, true);
                vrfg.preparedEdit(listOfFinancialGoalsFounded.get(row));
                vrfg.setVisible(true);
                formWindowOpened(null);
            }else{
                JOptionPane.showMessageDialog(null,"Erro: Não é possível alterar uma meta cumprida!");
            }
        }
    }//GEN-LAST:event_jChangeButtonActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        int row = jTableGoals.getSelectedRow();
        if(row <= -1){
            JOptionPane.showMessageDialog(null, "Para excluir uma meta financeira é necessário selecioná-la!");
        }else{
            if(JOptionPane.showConfirmDialog(null, "Deseja apagar a meta financeira " + listOfFinancialGoalsFounded.get(row).getName() +
                    "?", "Apagar meta ?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                try{
                    new FinancialGoalDAO().delete(listOfFinancialGoalsFounded.get(row));
                    c.getListOfFinancialGoal().remove(listOfFinancialGoalsFounded.get(row));
                    JOptionPane.showMessageDialog(null, "Meta financeira excluída com sucesso!");
                    formWindowOpened(null);
                }catch (SQLException | ClassNotFoundException ex){
                    JOptionPane.showMessageDialog(null, "Erro: Não foi possível excluir esta meta financeira.");
                }
            }
        }
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void jReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReturnButtonActionPerformed
        formWindowOpened(null);
    }//GEN-LAST:event_jReturnButtonActionPerformed

    private void jCheckBoxAllGoalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAllGoalsActionPerformed

    }//GEN-LAST:event_jCheckBoxAllGoalsActionPerformed

    private void jCheckBoxCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCompletedActionPerformed

    }//GEN-LAST:event_jCheckBoxCompletedActionPerformed

    private void jCheckBoxCurrentGoalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCurrentGoalsActionPerformed

    }//GEN-LAST:event_jCheckBoxCurrentGoalsActionPerformed

    private void jRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterButtonActionPerformed
        ViewRegisterFinancialGoal vrlfg = new ViewRegisterFinancialGoal(null, true);
        vrlfg.setVisible(true);
        formWindowOpened(null);
    }//GEN-LAST:event_jRegisterButtonActionPerformed

    private void fillTable(ArrayList<FinancialGoal> listOfFinancialGoals){
        DefaultTableModel dftm = (DefaultTableModel) jTableGoals.getModel();

        while(dftm.getRowCount() > 0){
            dftm.removeRow(0);
        }

        for(FinancialGoal fg : listOfFinancialGoals){
            addRow(fg, dftm);
        }
    }

    private static void addRow(FinancialGoal fg, DefaultTableModel dftm) {
        String [] row = {fg.getName(), fg.getDescription(), ValueFormat.displayValueFormat(fg.getValue()), ValueFormat.displayValueFormat(fg.getActualValue()),
                DateFormat.formatDateToString(fg.getInicialDate()), DateFormat.formatDateToString(fg.getFinalDate()),
                String.valueOf(fg.calculateRemainingInstallments())};
        dftm.addRow(row);
    }

    private void fillListFounded() {
        for(FinancialGoal fg : listOfFinancialGoals){
            if(jCheckBoxAllGoals.isSelected() || jCheckBoxCompleted.isSelected() && fg.getCompleted() || jCheckBoxCurrentGoals.isSelected() && !fg.getCompleted()){
                listOfFinancialGoalsFounded.add(fg);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewListFinancialGoals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewListFinancialGoals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewListFinancialGoals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewListFinancialGoals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewListFinancialGoals dialog = new ViewListFinancialGoals(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jChangeButton;
    private javax.swing.JCheckBox jCheckBoxAllGoals;
    private javax.swing.JCheckBox jCheckBoxCompleted;
    private javax.swing.JCheckBox jCheckBoxCurrentGoals;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JButton jExitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jRegisterButton;
    private javax.swing.JButton jReturnButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTable jTableGoals;
    // End of variables declaration//GEN-END:variables
    private ArrayList<FinancialGoal> listOfFinancialGoals;
    private ArrayList<FinancialGoal> listOfFinancialGoalsFounded;
    private Client c;
}
