/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.vianna.finance.view.expenses;

import br.edu.vianna.finance.dao.imp.ExpenseDAO;
import br.edu.vianna.finance.dao.imp.IncomeDAO;
import br.edu.vianna.finance.model.finances.Expense;
import br.edu.vianna.finance.model.finances.Income;
import br.edu.vianna.finance.model.users.Client;
import br.edu.vianna.finance.utils.dateForm.DateFormat;
import br.edu.vianna.finance.utils.valueForm.ValueFormat;
import br.edu.vianna.finance.view.viewPrincipal;
import java.awt.Color;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author Renan Guedes
 */
public class ViewListExpenses extends javax.swing.JDialog {

    /**
     * Creates new form ViewListExpenses
     */
    public ViewListExpenses(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.darkGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jExitButton = new javax.swing.JButton();
        jChangeButton = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();
        jRegisterButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExpenses = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMonthField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jYearField = new javax.swing.JTextField();
        jSearchButton = new javax.swing.JButton();
        jReturnButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelTotalValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(76, 76, 76));
        setMinimumSize(new java.awt.Dimension(803, 630));
        setPreferredSize(new java.awt.Dimension(803, 630));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(76, 76, 76));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(632, 49));

        jExitButton.setBackground(new java.awt.Color(0, 102, 51));
        jExitButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-Button-cancel.png"))); // NOI18N
        jExitButton.setText("Sair");
        jExitButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jExitButton.setMaximumSize(new java.awt.Dimension(82, 29));
        jExitButton.setMinimumSize(new java.awt.Dimension(82, 29));
        jExitButton.setPreferredSize(new java.awt.Dimension(110, 29));
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jChangeButton.setBackground(new java.awt.Color(0, 102, 51));
        jChangeButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jChangeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-Button-alter.png"))); // NOI18N
        jChangeButton.setText("Alterar");
        jChangeButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jChangeButton.setPreferredSize(new java.awt.Dimension(110, 29));
        jChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChangeButtonActionPerformed(evt);
            }
        });

        jDeleteButton.setBackground(new java.awt.Color(0, 102, 51));
        jDeleteButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-Button-delete.png"))); // NOI18N
        jDeleteButton.setText("Excluir");
        jDeleteButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jDeleteButton.setMaximumSize(new java.awt.Dimension(82, 29));
        jDeleteButton.setMinimumSize(new java.awt.Dimension(82, 29));
        jDeleteButton.setPreferredSize(new java.awt.Dimension(110, 29));
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });

        jRegisterButton.setBackground(new java.awt.Color(0, 102, 51));
        jRegisterButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRegisterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-Button-check.png"))); // NOI18N
        jRegisterButton.setText("Cadastrar");
        jRegisterButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jRegisterButton.setMaximumSize(new java.awt.Dimension(82, 29));
        jRegisterButton.setMinimumSize(new java.awt.Dimension(82, 29));
        jRegisterButton.setPreferredSize(new java.awt.Dimension(110, 29));
        jRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTableExpenses.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTableExpenses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Despesa", "Descrição", "Valor", "Tipo de Despesa", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableExpenses.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jTableExpenses);

        jPanel4.setBackground(new java.awt.Color(0, 102, 51));
        jPanel4.setPreferredSize(new java.awt.Dimension(354, 70));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LISTA DE DESPESAS");
        jLabel5.setMaximumSize(new java.awt.Dimension(354, 42));
        jLabel5.setMinimumSize(new java.awt.Dimension(354, 42));
        jLabel5.setPreferredSize(new java.awt.Dimension(354, 42));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(76, 76, 76));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(292, 127));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mês: ");

        jMonthField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMonthField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ano:");

        jYearField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jYearField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jSearchButton.setBackground(new java.awt.Color(0, 102, 51));
        jSearchButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jSearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-Button-search.png"))); // NOI18N
        jSearchButton.setText("Pesquisar");
        jSearchButton.setMaximumSize(new java.awt.Dimension(82, 29));
        jSearchButton.setMinimumSize(new java.awt.Dimension(82, 29));
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });

        jReturnButton.setBackground(new java.awt.Color(0, 102, 51));
        jReturnButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jReturnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-Button-return.png"))); // NOI18N
        jReturnButton.setText("  Voltar");
        jReturnButton.setMaximumSize(new java.awt.Dimension(82, 29));
        jReturnButton.setMinimumSize(new java.awt.Dimension(82, 29));
        jReturnButton.setPreferredSize(new java.awt.Dimension(110, 29));
        jReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReturnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jMonthField, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jYearField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSearchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jReturnButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jMonthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(76, 76, 76));

        jLabel4.setBackground(new java.awt.Color(0, 102, 51));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Valor Total:");
        jLabel4.setOpaque(true);

        jLabelTotalValue.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTotalValue.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addComponent(jLabelTotalValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jMonthField.setText("");
        jYearField.setText("");
        jLabelTotalValue.setText("");
        try{
            c = (Client) viewPrincipal.getUser();
            listOfExpenses = new ExpenseDAO().searchClientExpenses(c);
            c.setListOfExpenses(listOfExpenses);
            fillTable(listOfExpenses);
            jLabelTotalValue.setText(ValueFormat.displayValueFormat(c.calculateTotalExpenses()));
        }catch (SQLException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro: não foi possível carregar suas receitas!");
        }
    }//GEN-LAST:event_formWindowOpened

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        try{
            if(jMonthField.getText().isBlank() || jYearField.getText().isBlank()){
                JOptionPane.showMessageDialog(rootPane, "Erro: Os campos mês e ano devem ser preenchidos!");
            }else if(!checkFields()){
                JOptionPane.showMessageDialog(rootPane, "Erro: Os campos mês e ano só aceitam valores numéricos.\nExemplo: Mês: 01 Ano: 2000");
            }else{
                listOfExpenses = c.returnExpensesPerMonthAndYear(jMonthField.getText(), jYearField.getText());
                jLabelTotalValue.setText(ValueFormat.displayValueFormat(c.calculateTotalExpensesByMonthAndYear(jMonthField.getText(), jYearField.getText())));
                fillTable(listOfExpenses);
            }
        }catch (SQLException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro: não foi possível carregar suas despesas!");
        }

    }//GEN-LAST:event_jSearchButtonActionPerformed

    private void jChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChangeButtonActionPerformed
        int row = jTableExpenses.getSelectedRow();
        if(row <= -1){
            JOptionPane.showMessageDialog(rootPane, "Para alterar uma despesa financeira é necessário selecioná-la!");
        }else{
            ViewRegisterExpense vre = new ViewRegisterExpense(null, true);
            vre.preparedEdit(listOfExpenses.get(row));
            vre.setVisible(true);
            formWindowOpened(null);
        }
    }//GEN-LAST:event_jChangeButtonActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        int row = jTableExpenses.getSelectedRow();
        if(row <= -1){
            JOptionPane.showMessageDialog(rootPane, "Para excluir uma despesa financeira é necessário selecioná-la!!");
        }else{
            if(JOptionPane.showConfirmDialog(rootPane, "Deseja apagar a despesa: " + listOfExpenses.get(row).getDescription() + " ?", "Apagar despesa ?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                try{
                    new ExpenseDAO().delete(listOfExpenses.get(row));
                    JOptionPane.showMessageDialog(rootPane, "Despesa excluída com sucesso!");
                    formWindowOpened(null);
                }catch (SQLException | ClassNotFoundException ex){
                    JOptionPane.showMessageDialog(rootPane, "Erro: Não foi possível excluir esta despesa.");
                }
            }
        }
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void jReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReturnButtonActionPerformed
        formWindowOpened(null);
    }//GEN-LAST:event_jReturnButtonActionPerformed

    private void jRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterButtonActionPerformed
        ViewRegisterExpense vre = new ViewRegisterExpense(null, true);
        vre.setVisible(true);
        formWindowOpened(null);
    }//GEN-LAST:event_jRegisterButtonActionPerformed

    private void fillTable(ArrayList<Expense> listOfExpenses){
        DefaultTableModel dftm = (DefaultTableModel) jTableExpenses.getModel();

        while(dftm.getRowCount() > 0){
            dftm.removeRow(0);
        }

        for(Expense e : listOfExpenses){
            if(!jMonthField.getText().isBlank() && !jYearField.getText().isBlank()){
                if(e.getDate().getMonthValue() == Integer.parseInt(jMonthField.getText()) && e.getDate().getYear() == Integer.parseInt(jYearField.getText())){
                    addRow(e, dftm);
                }
            }else if(jMonthField.getText().isBlank() && jYearField.getText().isBlank()){
                addRow(e, dftm);
            }
        }
    }

    private static void addRow(Expense e, DefaultTableModel dftm) {
        String [] row = {String.valueOf(e.getId()), e.getDescription(), ValueFormat.displayValueFormat(e.getValue()), e.getType().toString(), DateFormat.formatDateToString(e.getDate())};
        dftm.addRow(row);
    }

    private Boolean checkFields(){
        return DateFormat.validateMonth(jMonthField.getText()) && DateFormat.validadeYear(jYearField.getText());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewListExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewListExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewListExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewListExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewListExpenses dialog = new ViewListExpenses(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jChangeButton;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JButton jExitButton;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTotalValue;
    private javax.swing.JTextField jMonthField;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jRegisterButton;
    private javax.swing.JButton jReturnButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTable jTableExpenses;
    private javax.swing.JTextField jYearField;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Expense> listOfExpenses;
    private Client c;

}
